<script>
  import { createEventDispatcher } from 'svelte'

  export let open = false

  const dispatch = createEventDispatcher()

  const close = () => {
    dispatch('close')
  }

  const handleBackdropClick = (event) => {
    if (event.target === event.currentTarget) {
      close()
    }
  }

  const handleBackdropKeydown = (event) => {
    if (event.key === 'Escape') {
      event.preventDefault()
      close()
    }
  }
</script>

{#if open}
  <div
    class="modal-backdrop"
    role="dialog"
    aria-modal="true"
    tabindex="-1"
    on:click={handleBackdropClick}
    on:keydown={handleBackdropKeydown}
  >
    <section class="modal" role="document">
      <header class="modal__header">
        <h2>Workout YAML reference</h2>
        <button type="button" class="modal__close" on:click={close} aria-label="Close">×</button>
      </header>
      <div class="modal__content">
        <p>
          Define the workout structure with a root object containing a <code>title</code> and an
          ordered list of <code>rounds</code>.
        </p>

        <h3>Plan fields</h3>
        <ul>
          <li><code>preStartSeconds</code> (number, optional, default 0): Countdown before the first set.</li>
          <li><code>preStartLabel</code> (string, optional): Text shown during the pre-start countdown.</li>
          <li><code>defaultRepCounterMode</code> (string, optional, <code>swing</code> | <code>lockout</code> | <code>disabled</code>, default <code>disabled</code>): Default rep-counter mode applied to sets without an explicit override.</li>
          <li><code>enableRepCounter</code> (string, optional, <code>work</code> | <code>all</code>, default <code>work</code>): Phases where the rep counter should run (<code>work</code> phases only, or every phase).</li>
          <li><code>enableModeChanging</code> (boolean, optional, default <code>true</code>): Allow gesture-based mode changes globally; can be overridden per set.</li>
          <li><code>title</code> (string): Name of the workout.</li>
          <li><code>description</code> (string, optional): Short summary displayed in the planner.</li>
          <li><code>rounds</code> (array): Ordered rounds performed sequentially.</li>
        </ul>

        <h3>Round fields</h3>
        <ul>
          <li><code>id</code> (string, optional): Unique identifier; autogenerated when omitted.</li>
          <li><code>label</code> (string, optional): Display name shown in the planner.</li>
          <li><code>repetitions</code> (number, optional, default 1): How many times to repeat the round.</li>
          <li><code>restAfterSeconds</code> (number, optional, default 0): Rest after each round repeat.</li>
          <li><code>sets</code> (array): Ordered sets performed inside the round.</li>
        </ul>

        <h3>Set fields</h3>
        <ul>
          <li><code>id</code> (string, optional): Unique identifier; autogenerated when omitted.</li>
          <li><code>label</code> (string, optional): Name displayed in the timer.</li>
          <li><code>workSeconds</code> (number): Duration of the work interval in seconds.</li>
          <li><code>restSeconds</code> (number, optional, default 0): Rest between repetitions of the same set.</li>
          <li><code>repetitions</code> (number, optional, default 1): Repeat count for the set’s work/rest pair.</li>
          <li><code>transitionSeconds</code> (number, optional, default 0): Rest before the next set in the round.</li>
          <li><code>announcements</code> (array, optional): Voice prompts with <code>text</code> and <code>atSeconds</code> (seconds from the start of work; negative values count back from the end); optional <code>once</code> and <code>voice</code>.</li>
          <li><code>restAnnouncements</code> (array, optional): Voice prompts for rest phases (same structure as <code>announcements</code>).</li>
          <li><code>repCounterMode</code> (string, optional): Override the global mode for this set (<code>swing</code> | <code>lockout</code> | <code>disabled</code>).</li>
          <li><code>enableModeChanging</code> (boolean, optional): Whether gestures can change rep-counter mode during this set.</li>
        </ul>

        <h3>Example</h3>
<pre><code>title: Sample Session
description: Total-body push/pull focus
preStartSeconds: 10
preStartLabel: Get Ready
rounds:
  - label: Round 1
    repetitions: 2
    restAfterSeconds: 30
    sets:
      - label: Push Press
        workSeconds: 60
        restSeconds: 20
        repetitions: 3
        transitionSeconds: 45
        announcements:
          - text: \"Start Push Press\"
            atSeconds: 0
          - text: \"Halfway there\"
            atSeconds: 30
        restAnnouncements:
          - text: \"Row starts in 10 seconds\"
            atSeconds: -10
      - label: Plank
        workSeconds: 90
        transitionSeconds: 0</code></pre>

        <p>
          The timer flattens this structure into phases. Use <code>transitionSeconds</code> for breaks
          between sets and <code>restSeconds</code> for breaks between repetitions of the same set.
        </p>
      </div>
    </section>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: color-mix(in srgb, var(--color-bg) 35%, rgba(0, 0, 0, 0.6));
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1.5rem;
    z-index: 1000;
  }

  .modal {
    background: var(--color-surface-2);
    border: 1px solid var(--color-border);
    border-radius: 16px;
    max-width: min(720px, 100%);
    max-height: min(90vh, 720px);
    width: 100%;
    display: flex;
    flex-direction: column;
    color: var(--color-text-primary);
  }

  .modal__header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.25rem 1.5rem 1rem;
  }

  .modal__header h2 {
    margin: 0;
    font-size: 1.3rem;
  }

  .modal__close {
    border: none;
    background: transparent;
    color: var(--color-text-muted);
    font-size: 1.6rem;
    cursor: pointer;
    line-height: 1;
  }

  .modal__close:hover {
    color: var(--color-text-primary);
  }

  .modal__content {
    padding: 0 1.5rem 1.5rem;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 1rem;
    font-size: 0.95rem;
  }

  ul {
    margin: 0;
    padding-left: 1.2rem;
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  pre {
    margin: 0;
    padding: 1rem;
    border-radius: 12px;
    background: var(--color-surface-deep);
    border: 1px solid var(--color-border);
    overflow-x: auto;
  }

  code {
    font-family: 'Fira Code', 'SFMono-Regular', Menlo, Consolas, monospace;
    font-size: 0.9rem;
    color: var(--color-accent-soft);
  }

  pre code {
    color: inherit;
  }
</style>
